// examples/hello-react/src/components/App/App.jsx
import Button from "@/components/Button";

import reactLogo from "@/assets/react.svg";
import viteLogo from "/vite.svg";

import "./App.css";

function App({ payload = {} }) {
  const { settings, styles, i18n } = payload;

  // Using settings
  const title = settings?.title || "No title";

  // Using labels
  const label = i18n?.labels["example-label-key"] || "No label";

  // Using styles
  const color = styles?.value?.colors?.primary || "#333";

  return (
    <>
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>{title}</h1>
      <div className="color">
        <i style={{ backgroundColor: color }}></i>
        <span>{label}</span>
      </div>
      <div className="card">
        <Button />
        <p>
          Edit <code>@/components/App.jsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
      <textarea defaultValue={JSON.stringify(payload, null, 2)}></textarea>
    </>
  );
}

export default App;

// examples/hello-vue/src/App.vue
<script setup>
import HelloWorld from "./components/HelloWorld.vue";
</script>

<script>
export default {
  inject: ["payload"],
  data() {
    return {
      title: ''
    }
  },
  created() {
    this.title = this.payload.settings.title;
  }
}
</script>

<template>
  <div>
    <a href="https://vitejs.dev" target="_blank">
      <img src="./assets/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <HelloWorld :title="title" />
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
