// examples/hello-react/src/index.jsx
import { isReady } from "@everymundo/registry-script";

import React from "react";
import ReactDOM from "react-dom/client";

import '@/styles/global.css'
import App from "@/components/App";

isReady().then(async (payload) => {
  ReactDOM.createRoot(document.getElementById("root")).render(
    <React.StrictMode>
      <App payload={payload} />
    </React.StrictMode>
  );
});

// examples/hello-solid/src/index.jsx
/* @refresh reload */
import { isReady } from "@everymundo/registry-script";

import { render } from "solid-js/web";

import "./index.css";
import App from "./App";

const root = document.getElementById("root");

isReady().then(async (payload) => {
  render(() => <App payload={payload} />, root);
});
