// examples/hello-qwik/src/index.jsx
import { isReady } from "@everymundo/registry-script";

import "@builder.io/qwik/qwikloader.js";

import { render } from "@builder.io/qwik";
import { App } from "./components/App";
import "./styles/global.css";

isReady().then(async (payload) => {
  render(document.getElementById("app"), <App payload={payload} />);
});

// examples/hello-react/src/index.jsx
import { isReady } from "@everymundo/registry-script";

import React from "react";
import ReactDOM from "react-dom/client";

import '@/styles/global.css'
import App from "@/components/App";

isReady().then(async (payload) => {
  ReactDOM.createRoot(document.getElementById("root")).render(
    <React.StrictMode>
      <App payload={payload} />
    </React.StrictMode>
  );
});
